local M = {
	QUESTION_CLICK = "QUESTION_CLICK",
	QUESTION_SETFOCUS = "QUESTION_SETFOCUS",
	CHAT_MSG = "CHAT_MSG",
	CHAT_VOICE_MSG = "CHAT_VOICE_MSG",
	QUESTION_ANSWER = "QUESTION_ANSWER",
	QUESTION_TITLE ="QUESTION_TITLE", 
	DIGITAL_LOGIN = "DIGITAL_LOGIN",
	CHAT_QUIT = "CHAT_QUIT",
	CHANGE_NICKNAME = "CHANGE_NICKNAME",
	PLAYER_POSITION_RESET = "PLAYER_POSITION_RESET",
	PLAYER_POSITION_RECORD = "PLAYER_POSITION_RECORD",
	PLAYER_POSITION_TRANSFER = "PLAYER_POSITION_TRANSFER",
	PLAYER_POSITION_INIT = "PLAYER_POSITION_INIT",
}

return M